# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Settings
runtime_include_emi=true
runtime_include_kjs=true

# Gradle Configuration
artifact_name=mi-tweaks=forked

# Publishing
deploy_name=MI Tweaks
deploy_discord_icon=https://cdn.discordapp.com/emojis/1264330244450685009.webp
compatible_minecraft_versions=1.21.1
curseforge_project=1068413
curseforge_project_slug=mi-tweaks
curseforge_project_relations=tesseract-api-neoforge:required,modern-industrialization:required
modrinth_project=tJGIBxPC
modrinth_project_slug=mi-tweaks
modrinth_project_relations=tesseract-api:required,modern-industrialization:required

# NeoForge Environment
minecraft_version=1.21.1
minecraft_version_range=1.21.1
neoforge_version=21.1.228
parchment_mappings_minecraft_version=1.21
parchment_mappings_version=2024.07.28
loader_version_range=[4,)

# Mod Properties
mod_id=mi_tweaks
mod_name=MI Tweaks Forked
mod_group_id=net.swedz
mod_authors=Swedz (original), Atmos Studio (fork)
mod_description=A performance-focused fork of MI Tweaks for Modern Industrialization modpacks.
mod_github=https://github.com/atmosstudioteam/MI-Tweaks

# Dependencies
modern_industrialization_version=2.5.6
modern_industrialization_version_range=[2.5.6-, 2.6-)
grandpower_version=3.0.0
emi_version=1.1.24+1.21.1
emi_version_range=[1.1.24, 1.2-)
tesseract_version=1.12.15-1.21.1
tesseract_version_range=[1.12.15-, 1.13-)
kubejs_version=2101.7.2-build.290
